### ISSUE TITLE
Exception prozentualer Anteil Erstellen einer Initialisierung

### ISSUE THREAD

**Issue by sososophie97** [max-97/pse#166]
Der InputValidator akzeptiert nur double Eingaben für prozentuale Verteilungen. (Summe muss 1 sein)
Aber der ModelParser versucht aus der selben Eingabe Integer zu parsen und wirft Exception.
Wie soll die Verteilung angegeben werden: Als Bruchteil oder in Prozent?!

**Comment by MichelB97** [comment]
Ich werde das im Parser dann so umändern, dass überall, wo Anteile/Prozente auftreten, diese als Wert zwischen 0 und 1 eingegeben werden sollen. Ist das im InputValidator schon überall der Fall?

**Comment by sososophie97** [comment]
Falls ich nichts übersehen hab ist das der Fall ja.

**Comment by max-97** [comment]
Ich habe in #164 das umgeändert, sodass der InputValidator Eingaben der Form 20 (für 20%) und variable Parameter in der bisherigen Form annimmt. Dann müssen wir das Parsen nicht anpassen.

**Comment by max-97** [comment]
Außerdem habe ich die Summenüberprüfung entfernt, da es für variable Eingaben nicht funktioniert.
