### ISSUE TITLE
InputValidator akzeptiert nur Initialisierungen mit mind einem Startkapital

### ISSUE THREAD

**Issue by sososophie97** [max-97/pse#167]
Sollten nicht auch Initialisierungen ohne festgelegtes Startkapital akzeptiert werden?!

**Comment by simonhue** [comment]
Ich wusste nicht genau, wie der Parser das handhabt, habe es jetzt aber mal erlaubt.

**Comment by MichelB97** [comment]
Ich glaube, das wird im Parser zu einem Fehler führen, ich werde das am Wochenende dann noch beheben.
